[package]
name = "game_of_life_rust"
version = "0.1.0"
authors = ["StanEpp"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.3.14"
bit-vec="0.6.1"
rayon="1.3.0"
sdl2 = "0.33.0"
